services:
  bunkerweb:
    build:
      context: ../..
      dockerfile: ./src/bw/Dockerfile
    ports:
      - 80:8080/tcp
      - 443:8443/tcp
      - 443:8443/udp
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      - SERVER_NAME=app1.example.com
      - API_WHITELIST_IP=127.0.0.0/24 10.20.30.0/24
      - USE_BUNKERNET=no
      - USE_BLACKLIST=no
      - USE_WHITELIST=no
      - SEND_ANONYMOUS_REPORT=no
      - LOG_LEVEL=info
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_HOST=http://app1:8080
      - EXTERNAL_PLUGIN_URLS=https://github.com/bunkerity/bunkerweb-plugins/archive/refs/heads/dev.zip
      - CUSTOM_CONF_MODSEC_CRS_reqbody-suppress=SecRuleRemoveById 200002
    restart: "unless-stopped"
    networks:
      bw-universe:
        aliases:
          - bunkerweb
      bw-services:
        aliases:
          - bunkerweb

  bw-scheduler:
    build:
      context: ../..
      dockerfile: ./src/scheduler/Dockerfile
    depends_on:
      - bunkerweb
      - bw-docker
    volumes:
      - bw-data:/data
      - ./configs/server-http/hello.conf:/data/configs/server-http/hello.conf:ro
    environment:
      - DOCKER_HOST=tcp://bw-docker:2375
      - LOG_LEVEL=debug
    restart: "unless-stopped"
    networks:
      bw-universe:
        aliases:
          - bw-scheduler
      bw-docker:
        aliases:
          - bw-scheduler

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    restart: "unless-stopped"
    networks:
      bw-docker:
        aliases:
          - bw-docker

  app1:
    image: nginxdemos/nginx-hello
    restart: "unless-stopped"
    networks:
      bw-services:
        aliases:
          - app1

volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
