x-env: &env
  DATABASE_URI: "mariadb+pymysql://bunkerweb:secret@bw-db:3306/db"
  DOCKER_HOST: "tcp://bw-docker:2375"
  AUTOCONF_MODE: "yes"
  LOG_LEVEL: "debug"

services:
  bunkerweb:
    build:
      context: ../..
      dockerfile: ./src/bw/Dockerfile
    ports:
      - 80:8080/tcp
      - 443:8443/tcp
      - 443:8443/udp
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      - SERVER_NAME=
      - MULTISITE=yes
      - API_WHITELIST_IP=127.0.0.0/24 10.20.30.0/24
      - AUTOCONF_MODE=yes
      - USE_BUNKERNET=no
      - USE_BLACKLIST=no
      - USE_WHITELIST=no
      - SEND_ANONYMOUS_REPORT=no
      - LOG_LEVEL=info
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - EXTERNAL_PLUGIN_URLS=https://github.com/bunkerity/bunkerweb-plugins/archive/refs/heads/dev.zip
      - CUSTOM_CONF_MODSEC_CRS_reqbody-rule=SecRuleRemoveById 200002
    restart: "unless-stopped"
    networks:
      bw-universe:
        aliases:
          - bunkerweb
      bw-services:
        aliases:
          - bunkerweb

  bw-autoconf:
    build:
      context: ../..
      dockerfile: ./src/autoconf/Dockerfile
    depends_on:
      - bunkerweb
      - bw-docker
    environment:
      <<: *env
    restart: "unless-stopped"
    networks:
      bw-universe:
        aliases:
          - bw-autoconf
      bw-docker:
        aliases:
          - bw-autoconf

  bw-scheduler:
    build:
      context: ../..
      dockerfile: ./src/scheduler/Dockerfile
    depends_on:
      - bunkerweb
      - bw-docker
    volumes:
      - bw-data:/data
      - ./configs/server-http/hello.conf:/data/configs/server-http/hello.conf:ro
    environment:
      <<: *env
    restart: "unless-stopped"
    networks:
      bw-universe:
        aliases:
          - bw-scheduler
      bw-docker:
        aliases:
          - bw-scheduler

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    restart: "unless-stopped"
    networks:
      bw-docker:
        aliases:
          - bw-docker

  bw-db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=bunkerweb
      - MYSQL_PASSWORD=secret
    volumes:
      - bw-db:/var/lib/mysql
    restart: "unless-stopped"
    networks:
      bw-docker:
        aliases:
          - bw-db

  app1:
    image: nginxdemos/nginx-hello
    restart: "unless-stopped"
    networks:
      bw-services:
        aliases:
          - app1
    labels:
      - "bunkerweb.SERVER_NAME=app1.example.com"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.REVERSE_PROXY_URL=/"
      - "bunkerweb.REVERSE_PROXY_HOST=http://app1:8080"
      - bunkerweb.CUSTOM_CONF_MODSEC_CRS_ip-host=SecRuleRemoveById 920350

volumes:
  bw-data:
  bw-db:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
